version: 0.2
phases:
  build:
    commands:
      - env
      - cat /etc/fstab
      - cat /proc/mounts
      - mount | grep nfs
      - yum -y install nfs-utils
      - if [[ "${CODEBUILD_WEBHOOK_TRIGGER}" == "branch/develop" ]]; then DAGS_MOUNT=fs-0c75fb09.efs.us-west-2.amazonaws.com; fi
      - if [[ "${CODEBUILD_WEBHOOK_TRIGGER}" == "branch/master" ]]; then DAGS_MOUNT=fs-d93473dc.efs.us-west-2.amazonaws.com; fi
      - if [[ "${CODEBUILD_WEBHOOK_TRIGGER}" == "branch/main" ]]; then DAGS_MOUNT=fs-d93473dc.efs.us-west-2.amazonaws.com; fi
      - mkdir /dags && mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${DAGS_MOUNT}:/ /dags/
      - mount | grep nfs
      - rsync -avz --delete dags/ /dags/
      - rsync -avz --delete plugins/ /plugins/
