version: 0.2
phases:
  build:
    commands:
      - env | grep -i DAG
      - mount
      - mkdir /dags && mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-0c75fb09.efs.us-west-2.amazonaws.com:/ /dags/
      - rsync -avz --delete dags/ /dags/
      - rsync -avz --delete plugins/ /plugins/
