

version: "3"

services:
  # Airflow dependencies (s3, pgsql, redis, etc)
  s3:
    image: "minio/minio"
    volumes:
      - ./.data/s3_bucket:/data
    ports:
      - "9000:9000"
    command: server /data
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 10.193.232.20
      - 10.183.232.20

  redis:
    image: "redis:5.0.5"
    command: redis-server
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 10.193.232.20
      - 10.183.232.20

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./.data/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 10.193.232.20
      - 10.183.232.20

  # Airflow services
  webserver:
    build:
      context: .
      args:
        - ARTIFACTORY_USER
        - ARTIFACTORY_TOKEN
    image: local-airflow
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    depends_on:
      - postgres
      - redis
      - s3
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 10.193.232.20
      - 10.183.232.20
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgres://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - FERNET_KEY=pv6SnOI5u3cG19iL4hDd2IFbifx4cmQEy4xRoqvqic8=
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    command: webserver

  flower:
    image: local-airflow
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    depends_on:
      - redis
      - webserver
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 10.193.232.20
      - 10.183.232.20
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgres://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: local-airflow
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    depends_on:
      - webserver
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 10.193.232.20
      - 10.183.232.20
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgres://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - FERNET_KEY=pv6SnOI5u3cG19iL4hDd2IFbifx4cmQEy4xRoqvqic8=
    command: scheduler

  worker:
    image: local-airflow
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    depends_on:
      - webserver
      - scheduler
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 10.193.232.20
      - 10.183.232.20
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgres://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - FERNET_KEY=pv6SnOI5u3cG19iL4hDd2IFbifx4cmQEy4xRoqvqic8=
    command: worker
