drop table if exists `nvmailer`.`cms_cards`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`cms_cards` AS select `rt_cards`.`id` AS `id`,`rt_cards`.`cardId` AS `cardId`,`rt_cards`.`site_code` AS `site_code`,`rt_cards`.`cardTitle` AS `cardTitle`,`rt_cards`.`cardDescription` AS `cardDescription`,`rt_cards`.`merchant` AS `merchant`,`rt_cards`.`introApr` AS `introApr`,`rt_cards`.`active_introApr` AS `active_introApr`,`rt_cards`.`introAprPeriod` AS `introAprPeriod`,`rt_cards`.`active_introAprPeriod` AS `active_introAprPeriod`,`rt_cards`.`regularApr` AS `regularApr`,`rt_cards`.`variable` AS `variable`,`rt_cards`.`active_regularApr` AS `active_regularApr`,`rt_cards`.`annualFee` AS `annualFee`,`rt_cards`.`active_annualFee` AS `active_annualFee`,`rt_cards`.`monthlyFee` AS `monthlyFee`,`rt_cards`.`active_monthlyFee` AS `active_monthlyFee`,`rt_cards`.`balanceTransfers` AS `balanceTransfers`,`rt_cards`.`active_balanceTransfers` AS `active_balanceTransfers`,`rt_cards`.`balanceTransferFee` AS `balanceTransferFee`,`rt_cards`.`active_balanceTransferFee` AS `active_balanceTransferFee`,`rt_cards`.`balanceTransferIntroApr` AS `balanceTransferIntroApr`,`rt_cards`.`active_balanceTransferIntroApr` AS `active_balanceTransferIntroApr`,`rt_cards`.`balanceTransferIntroAprPeriod` AS `balanceTransferIntroAprPeriod`,`rt_cards`.`active_balanceTransferIntroAprPeriod` AS `active_balanceTransferIntroAprPeriod`,`rt_cards`.`creditNeeded` AS `creditNeeded`,`rt_cards`.`active_creditNeeded` AS `active_creditNeeded`,`rt_cards`.`imagePath` AS `imagePath`,`rt_cards`.`ratesAndFees` AS `ratesAndFees`,`rt_cards`.`rewards` AS `rewards`,`rt_cards`.`cardBenefits` AS `cardBenefits`,`rt_cards`.`onlineServices` AS `onlineServices`,`rt_cards`.`footNotes` AS `footNotes`,`rt_cards`.`layout` AS `layout`,`rt_cards`.`dateCreated` AS `dateCreated`,`rt_cards`.`dateUpdated` AS `dateUpdated`,`rt_cards`.`subCat` AS `subCat`,`rt_cards`.`catTitle` AS `catTitle`,`rt_cards`.`catDescription` AS `catDescription`,`rt_cards`.`catImage` AS `catImage`,`rt_cards`.`catImageAltText` AS `catImageAltText`,`rt_cards`.`syndicate` AS `syndicate`,`rt_cards`.`url` AS `url`,`rt_cards`.`applyByPhoneNumber` AS `applyByPhoneNumber`,`rt_cards`.`tPageText` AS `tPageText`,`rt_cards`.`private` AS `private`,`rt_cards`.`active` AS `active`,`rt_cards`.`deleted` AS `deleted`,`rt_cards`.`active_epd_pages` AS `active_epd_pages`,`rt_cards`.`active_show_epd_rates` AS `active_show_epd_rates`,`rt_cards`.`show_verify` AS `show_verify`,`rt_cards`.`commission_label` AS `commission_label`,`rt_cards`.`payout_cap` AS `payout_cap`,`rt_cards`.`card_level_id` AS `card_level_id`,`rt_cards`.`requires_approval` AS `requires_approval` from `cms`.`rt_cards`;

drop table if exists `nvmailer`.`cms_merchants`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`cms_merchants` AS select `cs_merchants`.`merchantid` AS `merchantid`,`cs_merchants`.`merchantname` AS `merchantname`,`cs_merchants`.`merchantcardpage` AS `merchantcardpage`,`cs_merchants`.`deleted` AS `deleted` from `cms`.`cs_merchants`;

drop table if exists `nvmailer`.`partner_cards`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`partner_cards` AS select `partner_cards`.`card_id` AS `card_id`, `partner_cards`.`time_modified` AS `time_modified`, `partner_cards`.`time_created` AS `time_created`, `partner_cards`.`acknowledged_time` AS `acknowledged_time`, `partner_cards`.`status` AS `status`, `partner_cards`.`deleted` AS `deleted` from `cccomus`.`partner_cards`;

drop table if exists `nvmailer`.`vw_partner_accounts`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`vw_partner_accounts` AS select `partner_accounts`.`account_id` AS `account_id`, `partner_accounts`.`name` AS `name`, `partner_accounts`.`account_type` AS `account_type`, `partner_accounts`.`status` AS `status`, `partner_accounts`.`created_time` AS `created_time`, `partner_accounts`.`deleted` AS `deleted` from `cccomus`.`partner_accounts`;

drop table if exists `nvmailer`.`vw_partner_account_types`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`vw_partner_account_types` AS select `partner_account_types`.`partner_account_type_id` AS `partner_account_type_id`, `partner_account_types`.`account_type` AS `account_type`, `partner_account_types`.`can_receive_email` AS `can_receive_email` from `cccomus`.`partner_account_types`;

drop table if exists `nvmailer`.`vw_partner_affiliates`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`vw_partner_affiliates` AS select `partner_affiliates`.`affiliate_id` AS `affiliate_id`,`partner_affiliates`.`account_id` AS `account_id`,`partner_affiliates`.`affiliate_type` AS `affiliate_type`,`partner_affiliates`.`ref_id` AS `ref_id`,`partner_affiliates`.`username` AS `username`,`partner_affiliates`.`password` AS `password`,`partner_affiliates`.`affiliate_representative_id` AS `affiliate_representative_id`,`partner_affiliates`.`first_name` AS `first_name`,`partner_affiliates`.`last_name` AS `last_name`,`partner_affiliates`.`company_name` AS `company_name`,`partner_affiliates`.`city` AS `city`,`partner_affiliates`.`state` AS `state`,`partner_affiliates`.`street` AS `street`,`partner_affiliates`.`address2` AS `address2`,`partner_affiliates`.`country` AS `country`,`partner_affiliates`.`zip` AS `zip`,`partner_affiliates`.`phone` AS `phone`,`partner_affiliates`.`fax` AS `fax`,`partner_affiliates`.`billing_first_name` AS `billing_first_name`,`partner_affiliates`.`billing_last_name` AS `billing_last_name`,`partner_affiliates`.`billing_company_name` AS `billing_company_name`,`partner_affiliates`.`billing_address1` AS `billing_address1`,`partner_affiliates`.`billing_address2` AS `billing_address2`,`partner_affiliates`.`billing_city` AS `billing_city`,`partner_affiliates`.`billing_state` AS `billing_state`,`partner_affiliates`.`billing_zip` AS `billing_zip`,`partner_affiliates`.`billing_country` AS `billing_country`,`partner_affiliates`.`referral_type` AS `referral_type`,`partner_affiliates`.`referral_detail` AS `referral_detail`,`partner_affiliates`.`tax` AS `tax`,`partner_affiliates`.`status` AS `status`,`partner_affiliates`.`commission_rate_id` AS `commission_rate_id`,`partner_affiliates`.`payment_type_id` AS `payment_type_id`,`partner_affiliates`.`payout_threshold` AS `payout_threshold`,`partner_affiliates`.`payout_name` AS `payout_name`,`partner_affiliates`.`ip` AS `ip`,`partner_affiliates`.`initials` AS `initials`,`partner_affiliates`.`restricted` AS `restricted`,`partner_affiliates`.`in_house` AS `in_house`,`partner_affiliates`.`time_inserted` AS `time_inserted`,`partner_affiliates`.`time_modified` AS `time_modified`,`partner_affiliates`.`deleted` AS `deleted`,`partner_affiliates`.`email` AS `email` from `cccomus`.`partner_affiliates`;

drop table if exists `nvmailer`.`vw_partner_card_affiliate_map`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`vw_partner_card_affiliate_map` AS select `partner_card_affiliate_map`.`affiliate_id` AS `affiliate_id`,`partner_card_affiliate_map`.`card_id` AS `card_id`,`partner_card_affiliate_map`.`status` AS `status`,`partner_card_affiliate_map`.`date_requested` AS `date_requested`,`partner_card_affiliate_map`.`approver_user_id` AS `approver_user_id`,`partner_card_affiliate_map`.`time_approved` AS `time_approved` from `cccomus`.`partner_card_affiliate_map`;

drop table if exists `nvmailer`.`vw_partner_card_website_map`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`vw_partner_card_website_map` AS select `partner_card_website_map`.`card_website_map_id` AS `card_website_map_id`,`partner_card_website_map`.`website_id` AS `website_id`,`partner_card_website_map`.`card_id` AS `card_id`,`partner_card_website_map`.`status` AS `status` from `cccomus`.`partner_card_website_map`;

drop table if exists `nvmailer`.`vw_partner_users`;
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`vw_partner_users` AS select `partner_users`.`user_id` AS `user_id`,`partner_users`.`account_id` AS `account_id`,`partner_users`.`username` AS `username`,`partner_users`.`password` AS `password`,`partner_users`.`password_hash` AS `password_hash`,`partner_users`.`first_name` AS `first_name`,`partner_users`.`last_name` AS `last_name`,`partner_users`.`email` AS `email`,`partner_users`.`created_time` AS `created_time`,`partner_users`.`deleted` AS `deleted`,`partner_users`.`can_login` AS `can_login` from `cccomus`.`partner_users`;

drop table if exists `nvmailer`.`vw_partner_websites`;

CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `nvmailer`.`vw_partner_websites` AS select `partner_websites`.`website_id` AS `website_id`,`partner_websites`.`affiliate_id` AS `affiliate_id`,`partner_websites`.`sub_account_id` AS `sub_account_id`,`partner_websites`.`name` AS `name`,`partner_websites`.`url` AS `url`,`partner_websites`.`description` AS `description`,`partner_websites`.`estimated_traffic_volume_id` AS `estimated_traffic_volume_id`,`partner_websites`.`approval_status` AS `approval_status`,`partner_websites`.`status` AS `status`,`partner_websites`.`api_key` AS `api_key`,`partner_websites`.`content_type` AS `content_type`,`partner_websites`.`traffic_source` AS `traffic_source`,`partner_websites`.`deleted` AS `deleted` from `cccomus`.`partner_websites`;
